### ISSUE TITLE
Different font - upper case/lower case - usage

### ISSUE THREAD

**Issue by manuignatius** [itzmanju/itzmanju.github.io#7]
In services page, the listing has different font face. E.g. 'C' for coverage is upper case while 'p' for photoshoot is lower case. Unify.

Dragonfly Photography provides different services including:
- Wedding day Coverage
- Pre-Wedding photoshoot
- Maternity photoshoot
- Newborn & Kids photoshoot
- Family photoshoot
- Corporate events
- Dance and Music events
- Birthdays and family functions
- Videography services

**Comment by itzmanju** [comment]
Done
