### ISSUE TITLE
Mobile view social icons are white on white background

### ISSUE THREAD

**Issue by notthetup** [itzmanju/itzmanju.github.io#8]
Also, the text in the cards is black on a black background.

![Screenshot 2019-03-17 14 03 09](https://user-images.githubusercontent.com/553140/54486124-91e1ef00-48be-11e9-84f2-05a4c65ff102.png)

**Comment by itzmanju** [comment]
<img width="329" alt="Screenshot 2019-03-23 at 5 11 00 PM" src="https://user-images.githubusercontent.com/2195462/54864195-b0e4f300-4d8e-11e9-8383-ca7947b60bcd.png">

Done!
