### ISSUE TITLE
Footer alignment is strange.

### ISSUE THREAD

**Issue by notthetup** [itzmanju/itzmanju.github.io#9]
Either the button, the copyright message, and the social button should be in the same line, else the copyright message needs a reason to be lower (maybe an \<hr\> on top or something)

![1 ](https://user-images.githubusercontent.com/553140/54486145-cbb2f580-48be-11e9-9c19-5d0e47dcc310.png)

**Comment by itzmanju** [comment]
Attempt footer redesign - Proposal to remove the 'Contact Us' button to a text

**Comment by itzmanju** [comment]
Add tabs - Home Footer

**Comment by itzmanju** [comment]
Fixed the footer alignment in desktop view - corrected the copyright/icons for balance. 
The mobile alignment issue is logged as issue#4
